# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('rank', models.CharField(blank=True, choices=[(b'7d', b'7d'), (b'6d', b'6d'), (b'5d', b'5d'), (b'4d', b'4d'), (b'3d', b'3d'), (b'2d', b'2d'), (b'1d', b'1d'), (b'1k', b'1k'), (b'2k', b'2k'), (b'3k', b'3k'), (b'4k', b'4k'), (b'5k', b'5k'), (b'6k', b'6k'), (b'7k', b'7k'), (b'8k', b'8k'), (b'9k', b'9k'), (b'10k', b'10k'), (b'11k', b'11k'), (b'12k', b'12k'), (b'13k', b'13k'), (b'14k', b'14k'), (b'15k', b'15k'), (b'16k', b'16k'), (b'17k', b'17k'), (b'18k', b'18k'), (b'19k', b'19k'), (b'20k', b'20k')], max_length=3)),
                ('gor', models.IntegerField(blank=True, null=True)),
                ('egd_id', models.CharField(blank=True, max_length=8)),
                ('kgs_nickname', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'ordering': ('gor', 'last_name'),
            },
        ),
    ]
